spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/full_marks?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
server:
  servlet:
    session:
      timeout: 1800
  #登录失效超时时间 默认30 min 此处单位:s
  port: 8079
  tomcat:
    max-http-form-post-size: 50000000

#logging:
#  config: fullMarksServer/fullMarks-web/src/main/resources/log4j.properties
#logging:
#  config: classpath:log4j2.xml
